// Convert a wizard-completed CompanyConfig into a server/.env body.
// One source of truth: ADAPTER_SPECS drives which fields get written.

import type { CompanyConfig } from './storage';
import { ADAPTER_SPECS, getProviderSpec } from './adapterSpecs';

interface EnvLine {
  key: string;
  value: string;
  comment?: string;
}

export function buildEnvLines(config: CompanyConfig): EnvLine[] {
  const lines: EnvLine[] = [];

  // ─── Header ───
  lines.push({ key: '__HEADER__', value: '', comment: 'Generated by The Company OS Setup Wizard' });
  lines.push({ key: '__HEADER2__', value: '', comment: `Created at ${new Date().toISOString()}` });

  // ─── Server ───
  lines.push({ key: '__S_SERVER__', value: '', comment: 'Server' });
  lines.push({ key: 'PORT', value: '3001' });
  lines.push({ key: 'NODE_ENV', value: 'development' });
  lines.push({ key: 'FRONTEND_URL', value: 'http://localhost:5173' });

  // ─── Database ───
  lines.push({ key: '__S_DB__', value: '', comment: 'Database' });
  lines.push({ key: 'DATABASE_TYPE', value: config.database.type });
  lines.push({ key: 'DATABASE_PATH', value: config.database.path || './data/company-os.db' });

  // ─── Company identity ───
  lines.push({ key: '__S_COMPANY__', value: '', comment: 'Company identity (from wizard)' });
  lines.push({ key: 'COMPANY_NAME',  value: quote(config.companyName) });
  lines.push({ key: 'FOUNDER_NAME',  value: quote(config.founderName) });
  lines.push({ key: 'FOUNDER_EMAIL', value: quote(config.founderEmail) });
  lines.push({ key: 'FOUNDER_ROLE',  value: quote(config.founderRole) });

  // ─── Budget ───
  lines.push({ key: '__S_BUDGET__', value: '', comment: 'Budget targets' });
  lines.push({ key: 'BUDGET_MONTHLY_EUR',    value: String(config.budget.monthly) });
  lines.push({ key: 'BUDGET_LIQUIDITY_EUR',  value: String(config.budget.liquidityTarget) });
  lines.push({ key: 'BUDGET_BREAKEVEN_EUR',  value: String(config.budget.breakEvenTarget) });

  // ─── Security ───
  lines.push({ key: '__S_SECURITY__', value: '', comment: 'Security' });
  lines.push({ key: 'JWT_SECRET', value: generateSecret(48), comment: 'auto-generated' });
  lines.push({ key: 'JWT_EXPIRES_IN', value: '30d' });
  lines.push({ key: 'KILL_SWITCH_ARMED', value: config.killSwitchArmed ? 'true' : 'false' });

  // ─── Adapters ───
  // Mock mode is OFF when ANY adapter is enabled with credentials, ON otherwise.
  const anyAdapterEnabled = ADAPTER_SPECS.some((s) => config.adapters[s.key]?.enabled);
  lines.push({ key: '__S_ADAPTERS__', value: '', comment: 'Adapters' });
  lines.push({ key: 'MOCK_MODE', value: anyAdapterEnabled ? 'false' : 'true' });

  for (const spec of ADAPTER_SPECS) {
    const cfg = config.adapters[spec.key];
    if (!cfg) continue;
    lines.push({ key: `__S_${spec.envPrefix}__`, value: '', comment: `${spec.title} adapter` });
    lines.push({ key: `${spec.envPrefix}_ENABLED`, value: cfg.enabled ? 'true' : 'false' });
    if (!cfg.enabled) continue;
    lines.push({ key: `${spec.envPrefix}_PROVIDER`, value: cfg.provider });
    const provider = getProviderSpec(spec.key, cfg.provider);
    if (!provider) continue;
    for (const field of provider.fields) {
      const value = cfg.credentials[field.key] ?? '';
      if (value === '') continue;
      lines.push({ key: field.envKey, value: needsQuote(value) ? quote(value) : value });
    }
  }

  // ─── Wizard lock ───
  lines.push({ key: '__S_SETUP__', value: '', comment: 'Setup wizard lock' });
  lines.push({ key: 'SETUP_COMPLETED', value: 'true' });
  lines.push({ key: 'SETUP_COMPLETED_AT', value: new Date().toISOString() });

  return lines;
}

export function serializeEnv(config: CompanyConfig): string {
  const lines = buildEnvLines(config);
  const out: string[] = [];
  for (const line of lines) {
    if (line.key.startsWith('__')) {
      if (line.comment) out.push(`\n# ${line.comment}`);
      continue;
    }
    if (line.comment) out.push(`${line.key}=${line.value}  # ${line.comment}`);
    else out.push(`${line.key}=${line.value}`);
  }
  return out.join('\n').trimStart() + '\n';
}

// ─── helpers ──────────────────────────────────────────────────────────

function quote(value: string): string {
  if (value === '') return '""';
  if (needsQuote(value)) return `"${value.replace(/"/g, '\\"')}"`;
  return value;
}

function needsQuote(value: string): boolean {
  return /[\s#"'`$]/.test(value);
}

function generateSecret(len = 48): string {
  const chars = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  let out = '';
  const crypto = (globalThis as { crypto?: Crypto }).crypto;
  if (crypto?.getRandomValues) {
    const buf = new Uint32Array(len);
    crypto.getRandomValues(buf);
    for (let i = 0; i < len; i++) out += chars[buf[i]! % chars.length];
    return out;
  }
  for (let i = 0; i < len; i++) out += chars[Math.floor(Math.random() * chars.length)];
  return out;
}
