/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'bg-primary': '#0A0A0F',
        'bg-secondary': '#111118',
        'bg-tertiary': '#1A1A24',
        'bg-elevated': '#22222E',
        'border-subtle': '#2A2A36',
        'border-default': '#3A3A4A',
        'border-strong': '#555568',
        'text-primary': '#F0F0F5',
        'text-secondary': '#9CA3AF',
        'text-tertiary': '#6B7280',
        'text-muted': '#4B5563',
        'accent-teal': '#2DD4BF',
        'accent-teal-glow': '#2DD4BF33',
        'accent-blue': '#3B82F6',
        'accent-purple': '#8B5CF6',
        'status-green': '#10B981',
        'status-green-glow': '#10B98133',
        'status-yellow': '#F59E0B',
        'status-yellow-glow': '#F59E0B33',
        'status-red': '#EF4444',
        'status-red-glow': '#EF444433',
        'status-orange': '#F97316',
        'chart-primary': '#2DD4BF',
        'chart-secondary': '#3B82F6',
        'chart-tertiary': '#8B5CF6',
        'chart-quaternary': '#F59E0B',
        'chart-grid': '#1A1A24',
        'chart-zero': '#2A2A36',
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        sans: ['"Inter"', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['"JetBrains Mono"', '"Fira Code"', 'monospace'],
      },
      spacing: {
        'space-1': '4px',
        'space-2': '8px',
        'space-3': '12px',
        'space-4': '16px',
        'space-5': '20px',
        'space-6': '24px',
        'space-8': '32px',
        'space-10': '40px',
        'space-12': '48px',
        'sidebar': '240px',
        'sidebar-collapsed': '64px',
        'kpi-bar': '72px',
      },
      borderRadius: {
        'card': '12px',
        'button': '8px',
        'input': '8px',
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
      },
      maxWidth: {
        'container': '1440px',
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        'card': '0 8px 32px rgba(0,0,0,0.4)',
        'glow-teal': '0 0 6px #2DD4BF33',
        'glow-green': '0 0 6px #10B98133',
        'glow-red': '0 0 6px #EF4444',
        'glow-yellow': '0 0 6px #F59E0B33',
        'kill': '0 0 20px #EF444466',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
        "pulse-red": {
          "0%, 100%": { opacity: "1", boxShadow: "0 0 6px #EF444433" },
          "50%": { opacity: "0.5", boxShadow: "0 0 12px #EF444466" },
        },
        "pulse-status": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.6" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
        "pulse-red": "pulse-red 2s ease-in-out infinite",
        "pulse-status": "pulse-status 2s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
